### ISSUE TITLE
如果我在页面放三个穿梭框，那么他们不能独立分开操作，这块是不是没有做相应的判断处理？

### ISSUE THREAD

**Issue by huizi666** [glud123/tree-transfer#1]
如果我在页面放三个穿梭框，那么他们不能独立分开操作，这块是不是没有做相应的判断处理？

**Comment by glud123** [comment]
> 如果我在页面放三个穿梭框，那么他们不能独立分开操作，这块是不是没有做相应的判断处理？

实在抱歉现在才回复，当时开发这个组件的时候没有考虑这种场景。如果有需要我会进行修正
